version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiqfome
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/aiqfome
      PORT: 3333
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "3333:3333"
    depends_on:
      - db
    command: sh -c "echo 'Rodando migrações...' && yarn prisma migrate deploy && echo 'Iniciando aplicação...' && yarn start:prod"

volumes:
  postgres-data:
